config/routes.rb
Rails.application.routes.draw do

  get "/",                          to: "home#index",           as: :root

  get "/users",                     to: "users#index",          as: :users
  get "/users/new",                 to: "users#new",            as: :new_user
  post "/users/create",             to: "users#create"
  get "users/:id",                  to: "users#show",           as: :user

  get "/login",                     to: "sessions#new",         as: :login

  get "/auth/:provider/callback",   to: "sessions#create",      as: :connect
  post "/auth/:developer/callback", to: "sessions#create"
  get "/logout",                    to: "sessions#destroy",     as: :logout

  get '/vimeo/index',               to: "vimeo#index",          as: :vimeo
  get '/vimeo/search',              to: "vimeo#search",         as: :vimeo_search
  get '/vimeo/new',                 to: "vimeo#new",            as: :new_vimeo
  post '/vimeo/create',             to: "vimeo#create",         as: :create_vimeo
  get '/vimeo/update',              to: "vimeo#update"
  patch '/vimeo/edit',              to: "vimeo#edit"
  delete '/vimeo/destroy',          to: "vimeo#destroy"
  get '/vimeo/show',                to: "vimeo#show",           as: :show_vimeo

  get '/twitter/new',               to: 'twitter#new',          as: :new_twitter
  get '/twitter/search',            to: 'twitter#show',         as: :twitter_search
  post '/twitter/:feed_uid',        to: 'twitter#create',       as: :twitter

  get '/instagram/index',           to: "instagram#index",      as: :instagram
  get '/instagram/search',          to: "instagram#search",     as: :instagram_search
  get '/instagram/new',             to: "instagram#new",        as: :new_instagram
  post '/instagram/new',            to: "instagram#create"
  get '/instagram/show',            to: "instagram#show",       as: :show_instagram

  get '/githubs/new',               to: 'githubs#new',          as: :new_github
  get '/githubs/search',            to: 'githubs#show',         as: :githubs_search
  post '/githubs/',                 to: 'githubs#create',       as: :github
  get '/githubs/feed',              to: 'githubs#feed'

  post 'subscriptions/:feed_uid',   to: 'subscriptions#create', as: :subscription

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :current_user

  include HTTParty
  #Beemo.configuration[:access_token] = ENV["VIMEO_ACCESS_TOKEN"]

  def index
    if session[:user_id]

      load_vimeo_data
      load_twitter_data if current_user.providers.find_by(name: "twitter")
      load_insta_data if current_user.providers.find_by(name: "instagram")

      @posts = current_user.posts.order(posted_time: :desc) #.limit(20)
    end
  end

  private

  # TWITTER

  def find_twitter_provider
    @provider = Provider.find_by_name_and_user_id("twitter", session[:user_id])
  end

  def create_twitter_client
    find_twitter_provider

    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_API_KEY"]
      config.consumer_secret     = ENV["TWITTER_API_SECRET"]
      config.access_token        = @provider.token
      config.access_token_secret = @provider.secret
    end
  end

  # only query api for newest tweets:
  # keep track of timestamp for a user
  # grab everything since then
  def load_twitter_data
    create_twitter_client
    twitter_feeds = current_user.feeds.where(provider: "twitter")

    twitter_feeds.each do |feed|
      @client.user_timeline(feed.uid.to_i).each do |tweet|
        feed.posts.find_or_create_by(
          author_name: tweet.user.name,
          author_handle: tweet.user.handle,
          author_profile_pic: tweet.user.profile_image_uri.to_s,
          content: tweet.text,
          uid: tweet.id.to_s,
          posted_time: tweet.created_at
        )
      end
    end
  end

  # VIMEO

  def load_vimeo_data
    # get vimeo Feed objects only
    vimeo_feeds = current_user.feeds.find_all{ |feed| feed.provider == "vimeo" }
    # Get vimeo Feed uid's for searching api
    vimeo_uids = vimeo_feeds.collect { |feed| feed.uid }
    # Searching vimeo api with vimeo uids, returns parsed vimeo json obejct
    @vimeo_vids = vimeo_uids.collect { |uid| HTTParty.get("http://vimeo.com/api/v2/" + uid + "/videos.json") }

    ###### Getting info out of nested data structure ######
    @filtered_videos = @vimeo_vids.collect do |httparty|
     httparty.collect do |video_object|
       filter_video_response(video_object)
     end
    end
    @filtered_videos.flatten!
    create_vimeo_posts(@filtered_videos)
  end

  def filter_video_response(raw_video_object)
    filtered_video_object = {}
    filtered_video_object[:title] = raw_video_object["title"]
    filtered_video_object[:uid] = raw_video_object["id"]
    filtered_video_object[:url] = raw_video_object["url"]
    filtered_video_object[:thumbnail] = raw_video_object["thumbnail_medium"]
    filtered_video_object[:username] = raw_video_object["user_name"]
    filtered_video_object[:upload_date] = DateTime.strptime(raw_video_object["upload_date"],  '%Y-%m-%d %H:%M:%S')
    filtered_video_object[:user_id] = raw_video_object["user_id"]
    return filtered_video_object
  end

  def create_vimeo_posts(filtered_videos)
    filtered_videos.each do |video|
      feed_object = Feed.find_by(uid: video[:user_id].to_s)
      Post.find_or_create_by(author_name: video[:username],
                  posted_time: video[:upload_date],
                  content: video[:thumbnail],
                  uid: video[:uid].to_s,
                  feed_id: feed_object.id)
    end
  end

  # INSTA

  def load_insta_data
    create_instagram_client
    instagram_feeds = current_user.feeds.where(provider: "instagram")

    instagram_feeds.each do |feed|
      Instagram.client.user_recent_media(feed.uid.to_i).each do |ig|
        feed.posts.find_or_create_by(author_name: ig["user"]["username"],
        author_handle: ig["user"]["username"],
        author_profile_pic: ig["user"]["profile_picture"],
        content: ig["images"]["low_resolution"]["url"],
        uid: ig["id"],
        posted_time: Time.at(ig[:created_time].to_i)
        )
      end
    end
  end

  def create_instagram_client
    @insta_provider = Provider.find_by_name_and_user_id("instagram", session[:user_id])

    Instagram.configure do |config|
      config.client_id = ENV["INSTAGRAM_CLIENT_ID"]
      config.client_secret = ENV["INSTAGRAM_API_SECRET"]
      config.access_token =  @insta_provider.token
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_guest_index.html.erb
<script>
  var self = window;

  ;(function(self) {

    var canvas, context, wave1 = [], wave2 = [], wave3 = [],
    mouse = { x: innerWidth * 0.5, y: innerHeight * 0.5 }, angle = 0,
    mouseDown = interactive = true, FPS = 60;

    /*
     * Init.
     */

    function init() {

      var body = document.querySelector('body');

      canvas = document.createElement('canvas');

      canvas.width = innerWidth;
      canvas.height = innerHeight;

      canvas.style.position = 'absolute';
      canvas.style.top = 50;
      // canvas.style.top = 0;
      canvas.style.bottom = 0;
      canvas.style.left = 0;
      canvas.style.right = 0;
      canvas.style.zIndex = -1;
      canvas.style.cursor = 'n-resize';

          body.appendChild(canvas);

      // Browser supports canvas?
      if(!!(capable)) {

        context = canvas.getContext('2d');

        // Events
        if('ontouchmove' in window) {

          canvas.addEventListener('touchstart', onTouchStart, false);
          canvas.addEventListener('touchend', onTouchEnd, false);
          canvas.addEventListener('touchmove', onTouchMove, false);

        }

        else {

          canvas.addEventListener('mousedown', onMouseDown, false);
          canvas.addEventListener('mouseup', onMouseUp, false);
          canvas.addEventListener('mousemove', onMouseMove, false);

        }

        window.onresize = onResize;

        createWaves();

      }

      else {

        console.error('Please, update your browser for seeing this animation.');

      }

    }

    /*
     * Checks if browser supports canvas element.
     */

    function capable() {

      return canvas.getContext && canvas.getContext('2d');

    }

    /*
     * On resize window event.
     */

    function onResize() {

      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;

    }

    /*
     * Mouse down event.
     */

    function onMouseDown(event) {

      event.preventDefault();

      mouseDown = true;

    }

    /*
     * Mouse up event.
     */

    function onMouseUp(event) {

      event.preventDefault();

      mouseDown = false;

    }

    /*
     * Mouse move event.
     */

    function onMouseMove(event) {

      event.preventDefault();

      mouse.x = event.pageX - canvas.offsetLeft;
      mouse.y = event.pageY - canvas.offsetTop;

      if(interactive)

        mouseDown = interactive = false;

    }

    /*
     * Touch start event.
     */

    function onTouchStart(event) {

      event.preventDefault();

      mouseDown = true;

    }

    /*
     * Touch end event.
     */

    function onTouchEnd(event) {

      event.preventDefault();

      mouseDown = false;

    }

    /*
     * Touch move event.
     */

    function onTouchMove(event) {

      event.preventDefault();

      mouse.x = event.touches[0].pageX - canvas.offsetLeft;
      mouse.y = event.touches[0].pageY - canvas.offsetTop;

      if(interactive)

        mouseDown = interactive = false;

    }

    /*
     * Create waves.
     */

    function createWaves() {

      var totalPoints = Math.round(canvas.width / 170);

      for(var quantity = 0, len = totalPoints; quantity < len; quantity++)

        // First wave
        wave1.push({

          x: canvas.width * quantity / (len - 1),
          y: canvas.height * 0.5 - 20,
          vy: Math.random() * 10,

          depth: canvas.height * 0.5

        });

      for(var quantity = 0, len = totalPoints; quantity < len; quantity++)

        // Second wave
        wave2.push({

          x: canvas.width * quantity / (len - 1),
          y: canvas.height * 0.5,
          vy: Math.random() * 10,

          depth: canvas.height * 0.5

        });

      for(var quantity = 0, len = totalPoints; quantity < len; quantity++)

        // Third wave
        wave3.push({

          x: canvas.width * quantity / (len - 1),
          y: canvas.height * 0.5 + 20,
          vy: Math.random() * 10,

          depth: canvas.height * 0.5

        });

      wave();

    }

    /*
     * Loop logic.
     */

    function wave() {

      clear();
      update();
      render();

      requestAnimFrame(wave);

    }

    /*
     * Clear the whole screen.
     */

    function clear() {

      context.clearRect(0, 0, innerWidth, innerHeight);

    };

    /*
     * Update the waves.
     */

    function update() {

        var ease, friction, threshold;

      friction = 0.99;
      threshold = interactive ? Math.round(canvas.width / 4.5) : 280;

      if(interactive) {

        angle += 0.05;

        mouse.x = canvas.width * 0.5 + Math.sin(angle) * canvas.width * 0.2;
        mouse.y = (canvas.height * 0.5 - 50) + Math.sin(angle) * canvas.height * 0.2;

      }

      for(var index = 0; index < (wave1.length || wave2.length || wave3.length); index++) {

        var point1 = wave1[index];
        var point2 = wave2[index];
        var point3 = wave3[index];

        point1.y += point1.vy;
        point2.y += point2.vy;
        point3.y += point3.vy;

        // Ease
        point1.vy += (point1.depth - point1.y) * (interactive ? 0.03 : 0.009);
        point2.vy += (point2.depth - point2.y) * (interactive ? 0.02 : 0.008);
        point3.vy += (point3.depth - point3.y) * (interactive ? 0.01 : 0.007);

        // Friction
        point1.vy *= friction;
        point2.vy *= friction;
        point3.vy *= friction;

        // Threshold
        if(distanceTo(mouse, point1) < threshold && mouseDown)

          point1.vy += (mouse.y - point1.y) * (interactive ? 0.03 : 0.009);

        if(distanceTo(mouse, point2) < threshold && mouseDown)

          point2.vy += (mouse.y - point2.y) * (interactive ? 0.02 : 0.008);

        if(distanceTo(mouse, point3) < threshold && mouseDown)

          point3.vy += (mouse.y - point3.y) * (interactive ? 0.01 : 0.007);

      }

    }

    /*
     * Render the waveS.
     */

    function render() {

      for(var wave = 0; wave < (wave1.length || wave2.length || wave3.length); wave++) {

        // Smooth bezier curves
        clear();

        context.save();
        context.globalAlpha = 0.5;
        context.fillStyle = '#f98f00';
        context.beginPath();

        context.moveTo(wave1[0].x, wave1[0].y);

        // Draw through N wave1
        for(var N = 1; N < wave1.length - 2; N++) {

          var xc = (wave1[N].x + wave1[N + 1].x) / 2;
          var yc = (wave1[N].y + wave1[N + 1].y) / 2;

          context.quadraticCurveTo(wave1[N].x, wave1[N].y, xc, yc);

        }

        context.quadraticCurveTo(wave1[wave1.length - 2].x, wave1[wave1.length - 2].y, wave1[wave1.length - 1].x, wave1[wave1.length - 1].y);
        context.lineTo(canvas.width, canvas.height);
        context.lineTo(0, canvas.height);
        context.lineTo(0, wave1[0].y);
        context.fill();
        context.restore();

        context.save();
        context.globalAlpha = 0.5;
        context.fillStyle = '#00fddc';
        context.beginPath();

        context.moveTo(wave2[0].x, wave2[0].y);

        // Draw through N wave2
        for(var N = 1; N < wave2.length - 2; N++) {

          var xc = (wave2[N].x + wave2[N + 1].x) / 2;
          var yc = (wave2[N].y + wave2[N + 1].y) / 2;

          context.quadraticCurveTo(wave2[N].x, wave2[N].y, xc, yc);

        }

        context.quadraticCurveTo(wave2[wave2.length - 2].x, wave2[wave2.length - 2].y, wave2[wave2.length - 1].x, wave2[wave2.length - 1].y);
        context.lineTo(canvas.width, canvas.height);
        context.lineTo(0, canvas.height);
        context.lineTo(0, wave2[0].y);
        context.fill();
        context.restore();

        context.save();
        context.globalAlpha = 0.5;
        context.fillStyle = '#05cdf8';
        context.beginPath();

        context.moveTo(wave3[0].x, wave3[0].y);

        // Draw through N wave3
        for(var N = 1; N < wave3.length - 2; N++) {

          var xc = (wave3[N].x + wave3[N + 1].x) / 2;
          var yc = (wave3[N].y + wave3[N + 1].y) / 2;

          context.quadraticCurveTo(wave3[N].x, wave3[N].y, xc, yc);

        }

        context.quadraticCurveTo(wave3[wave3.length - 2].x, wave3[wave3.length - 2].y, wave3[wave3.length - 1].x, wave3[wave3.length - 1].y);
        context.lineTo(canvas.width, canvas.height);
        context.lineTo(0, canvas.height);
        context.lineTo(0, wave3[0].y);
        context.fill();
        context.restore();

      }

    }

    /*
     * Distance between two wave1.
     */

    function distanceTo(pointA, pointB) {

      var dx = Math.abs(pointA.x - pointB.x);
      var dy = Math.abs(pointA.y - pointB.y);

      return Math.sqrt(dx * dx + dy * dy);

    };

    /*
     * Request new frame by Paul Irish.
     * 60 FPS.
     */

    window.requestAnimFrame = (function() {

      return  window.requestAnimationFrame       ||
          window.webkitRequestAnimationFrame ||
          window.mozRequestAnimationFrame    ||
          window.oRequestAnimationFrame      ||
          window.msRequestAnimationFrame     ||

          function(callback) {

            window.setTimeout(callback, 1000 / FPS);

          };

      })();

    window.addEventListener ? window.addEventListener('load', init, false) : window.onload = init;

  })(self);
</script>

<div class="container">
  <header>
    <h1>Stream</h1>
  </header>

  <div class = 'container' id='picbox'>
    <h2>Sign in or sign up with one of the providers below to see all your friends in one stream:</h2>
    <ul class="horizontal-nav search">
      <li><a href="/auth/github"><i class="fa fa-github-square fa-3x"></i></a></li>
      <li><a href="/auth/vimeo"><i class="fa fa-vimeo-square fa-3x"></i></a></li>
      <li><a href="/auth/twitter"><i class="fa fa-twitter-square fa-3x"></i></a></li>
      <li><a href="/auth/instagram"><i class="fa fa-instagram fa-3x"></i></a></li>
      <!-- <li><a href="/auth/developer">Developer<br>Strategy</a></li> -->
    </ul>
  </div>
</div>

app/views/home/_signed_in_index.html.erb
<div class="container">
  <ul class= "connect accounts">
    <li><h4>Connect More Feeds:</h4></li>
    <%#= link_to "Other Acct", "/users/" %>
    <%= link_to "Add Twitter", "/auth/twitter" %>
    <%= link_to "Add Vimeo", "/auth/vimeo" %>
    <%= link_to "Add Instagram", "/auth/instagram" %>
    <%= link_to "Add Github", "/auth/github" %>
  </ul>
  <ul class="search-users">
    <li><h4>Search For: </h4></li>
    <li><h4><i class="fa fa-twitter-square"></i><%= link_to "Twitter Users", new_twitter_path %></h4></li>
    <li><h4><i class="fa fa-vimeo-square"></i><%= link_to "Vimeo Users", new_vimeo_path %></h4></li>
    <li><h4><i class="fa fa-instagram"></i><%= link_to "Instagram Users", new_instagram_path %></h4></li>
    <li><h4><i class="fa fa-github-square"></i><%= link_to "Github Users", new_github_path %></h4></li>
  </ul>

  <!-- <div class="feed"> -->
  <% if @posts %>
    <% @posts.each do |post| %>
    <ul class="list-unstyled">
      <dl class="dl-horizontal">
        <dt>
          <!-- Add accessibility tag -->
          <img class="feed" src="<%= post.author_profile_pic %>">
        </dt>
        <dd>
          <%= post.author_name %>
          <small>
            @<%= post.author_handle %><br>
          </small>
          <% if post.feed.provider == "vimeo" %>
            <img class="visual-media" src="<%= post.content %>">
          <% elsif post.feed.provider == "instagram" %>
            <img class="visual-media" src="<%= post.content %>">
          <% else %>
            <%= post.content %>
          <% end %>
        </dd>
      </dl>
    <% end %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container">

  <% if session[:user_id] %>
    <%= render "home/signed_in_index" %>
  <% else %>
    <%= render "home/guest_index" %>
  <% end %>
</div>