config/routes.rb
Rails.application.routes.draw do

  get "/",                          to: "home#index",           as: :root

  get "/users",                     to: "users#index",          as: :users
  get "/users/new",                 to: "users#new",            as: :new_user
  post "/users/create",             to: "users#create"
  get "users/:id",                  to: "users#show",           as: :user

  get "/login",                     to: "sessions#new",         as: :login

  get "/auth/:provider/callback",   to: "sessions#create",      as: :connect
  post "/auth/:developer/callback", to: "sessions#create"
  get "/logout",                    to: "sessions#destroy",     as: :logout

  get '/vimeo/index',               to: "vimeo#index",          as: :vimeo
  get '/vimeo/search',              to: "vimeo#search",         as: :vimeo_search
  get '/vimeo/new',                 to: "vimeo#new",            as: :new_vimeo
  post '/vimeo/create',             to: "vimeo#create",         as: :create_vimeo
  get '/vimeo/update',              to: "vimeo#update"
  patch '/vimeo/edit',              to: "vimeo#edit"
  delete '/vimeo/destroy',          to: "vimeo#destroy"
  get '/vimeo/show',                to: "vimeo#show",           as: :show_vimeo

  get '/twitter/new',               to: 'twitter#new',          as: :new_twitter
  get '/twitter/search',            to: 'twitter#show',         as: :twitter_search
  post '/twitter/:feed_uid',        to: 'twitter#create',       as: :twitter

  get '/instagram/index',           to: "instagram#index",      as: :instagram
  get '/instagram/search',          to: "instagram#search",     as: :instagram_search
  get '/instagram/new',             to: "instagram#new",        as: :new_instagram
  post '/instagram/new',            to: "instagram#create"
  get '/instagram/show',            to: "instagram#show",       as: :show_instagram

  get '/githubs/new',               to: 'githubs#new',          as: :new_github
  get '/githubs/search',            to: 'githubs#show',         as: :githubs_search
  post '/githubs/',                 to: 'githubs#create',       as: :github
  get '/githubs/feed',              to: 'githubs#feed'

  post 'subscriptions/:feed_uid',   to: 'subscriptions#create', as: :subscription

end

app/controllers/vimeo_controller.rb
class VimeoController < ApplicationController
  before_action :current_user

  def index
  end

  def search
    create_vimeo_client
    @name = params['search']
  end

  def new
  end

  def create
    @vimeo_uid = params['subscription_uid']
    @vimeo_feed = Feed.find_or_create_by(uid: @vimeo_uid, provider: "vimeo")
    # @vimeo_feed.provider = "vimeo"
    if @vimeo_feed.save
      # Create join table relationship bt Feed and Subscription
      @vimeo_feed.subscriptions.create(user_id: session[:user_id], feed_id: @vimeo_feed.id)
      redirect_to root_path
    else
      render :new
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
    @name = params['search']
    create_vimeo_client
    @users_info = Beemo::User.search("#{@name}")
  end

  private

  def create_vimeo_client
    Provider.find_by(user_id: session[:user_id], name: "vimeo").token
  end


end

app/helpers/vimeo_helper.rb
module VimeoHelper
end

app/views/vimeo/create.html.erb
<h1>Vimeo#create</h1>
<p>Find me in app/views/vimeo/create.html.erb</p>

app/views/vimeo/destroy.html.erb
<h1>Vimeo#destroy</h1>
<p>Find me in app/views/vimeo/destroy.html.erb</p>

app/views/vimeo/edit.html.erb
<h1>Vimeo#edit</h1>
<p>Find me in app/views/vimeo/edit.html.erb</p>

app/views/vimeo/index.html.erb
<h1>Vimeo#index</h1>
<p>Find me in app/views/vimeo/index.html.erb</p>
<% @treehouse.each do |treehouse|%>
  <%= treehouse.name %>
<% end %>

app/views/vimeo/new.html.erb
<div class="container">
  <h1>Vimeo User Search</h1>

  <h3>Search by username</h3>
  <%= form_tag( show_vimeo_path, :method => :get ) do%>
    <p>
      <%= text_field_tag :search %>
      <%= submit_tag "Go", class: 'btn btn-default' %>
    </p>
  <% end %>
</div>

app/views/vimeo/search.html.erb
<h1>Vimeo Search Results</h1>

app/views/vimeo/show.html.erb
<div class="container">
  <h1>Vimeo Search Results</h1>

  <% @users_info.each do |user| %>
    <!-- This is the user's display name -->
    <h3><%= user.name %></h3>

    <!-- Profile pic conditional display -->
    <% if user.profile_pics != nil %>
      <img src="<%= user.profile_pics["sizes"][1]["link"] %>" alt="<%= user.name %> icon" />
    <% end %>

    <%= form_tag( create_vimeo_path ) do%>
      <p>
        <%= hidden_field_tag 'subscription_uid', user.uid %>
        <%= submit_tag "Subscribe", class: 'btn btn-default' %>
      </p>
    <% end %>


  <% end %>




  <p>
    <%= link_to "Back to Vimeo Search", new_vimeo_path %>
  </p>
</div>

app/views/vimeo/update.html.erb
<h1>Vimeo#update</h1>
<p>Find me in app/views/vimeo/update.html.erb</p>