config/routes.rb
Rails.application.routes.draw do

  get "/",                          to: "home#index",           as: :root

  get "/users",                     to: "users#index",          as: :users
  get "/users/new",                 to: "users#new",            as: :new_user
  post "/users/create",             to: "users#create"
  get "users/:id",                  to: "users#show",           as: :user

  get "/login",                     to: "sessions#new",         as: :login

  get "/auth/:provider/callback",   to: "sessions#create",      as: :connect
  post "/auth/:developer/callback", to: "sessions#create"
  get "/logout",                    to: "sessions#destroy",     as: :logout

  get '/vimeo/index',               to: "vimeo#index",          as: :vimeo
  get '/vimeo/search',              to: "vimeo#search",         as: :vimeo_search
  get '/vimeo/new',                 to: "vimeo#new",            as: :new_vimeo
  post '/vimeo/create',             to: "vimeo#create",         as: :create_vimeo
  get '/vimeo/update',              to: "vimeo#update"
  patch '/vimeo/edit',              to: "vimeo#edit"
  delete '/vimeo/destroy',          to: "vimeo#destroy"
  get '/vimeo/show',                to: "vimeo#show",           as: :show_vimeo

  get '/twitter/new',               to: 'twitter#new',          as: :new_twitter
  get '/twitter/search',            to: 'twitter#show',         as: :twitter_search
  post '/twitter/:feed_uid',        to: 'twitter#create',       as: :twitter

  get '/instagram/index',           to: "instagram#index",      as: :instagram
  get '/instagram/search',          to: "instagram#search",     as: :instagram_search
  get '/instagram/new',             to: "instagram#new",        as: :new_instagram
  post '/instagram/new',            to: "instagram#create"
  get '/instagram/show',            to: "instagram#show",       as: :show_instagram

  get '/githubs/new',               to: 'githubs#new',          as: :new_github
  get '/githubs/search',            to: 'githubs#show',         as: :githubs_search
  post '/githubs/',                 to: 'githubs#create',       as: :github
  get '/githubs/feed',              to: 'githubs#feed'

  post 'subscriptions/:feed_uid',   to: 'subscriptions#create', as: :subscription

end

app/controllers/githubs_controller.rb
class GithubsController < ApplicationController
  before_action :current_user

  def index
  end

  def new
    find_provider
    create_github_client
  end

  def show
    create_github_client
    @search_results = @client.search_users("#{params[:q]} in:login")
  end

  def create
    @feed = Feed.find_by_uid(params[:uid])

    if @feed
      current_user.subscriptions.create(feed_id: @feed.id)
    else
      current_user.feeds.create(username: params["username"], uid: params["uid"], provider: params["provider"])
    end
    redirect_to root_path
  end

  def feed
    create_github_client
    # @variable = Octokit.user_events("rmoshier")
    find_provider
    @client = Octokit::Client.new(:access_token => find_provider.token)
    github_feeds = current_user.feeds.where(provider: "github")
    github_feeds.each do |feed|
      Octokit.user_events(feed.uid.to_i).each do |event|
        # raise
        feed.posts.find_or_create_by(
        author_handle: event[:actor][:login],
        author_profile_pic: event[:actor][:avatar_url],
        content: event[:repo][:name]
      )
      end
    end
    # @posts = current_user.posts.limit(20)
  end

  private

  def find_provider
    @provider = Provider.find_by_name_and_user_id("github", session[:user_id])
  end

  def create_github_client
    @client = Octokit::Client.new(:access_token => find_provider.token)
  end

end

app/helpers/githubs_helper.rb
module GithubsHelper
end

app/views/githubs/feed.html.erb
<div class="container">
  <h1>Github Feed</h1>
<div class="container">
  <%= @posts %>
</div>

app/views/githubs/new.html.erb
<div class="container">
  <h1>Github User Search</h1>



<div class="container">
  <%= form_tag(githubs_search_path, method: "get") do %>
    <p>

      <%= text_field_tag :q, params[:q], :placeholder => "Search for user" %>
      <%= submit_tag "Go", class: 'btn btn-default' %>

    </p>
  <% end %>
</div>

app/views/githubs/show.html.erb
<%#= raise %>
<div class="container">
  <h1>Github Search Results</h1>

    <% @search_results[:items].each do |result| %>
      <div class='result row'>
      <h3><%= link_to result[:login], "http://github.com/#{result[:login]}", target: "_blank" %></h3>

      <% if result[:avatar_url] != nil %>
        <img class="github-icon" src="<%= result[:avatar_url] %>">
      <% end %>
      <%= form_tag(github_path) do %>
        <p>
          <%= hidden_field_tag 'username', result[:login], class: "github_name" %>
          <%= hidden_field_tag 'uid', result[:id], class: "github_id" %>
          <%= hidden_field_tag 'provider', "github", class: "github_provider"%>
          <%= submit_tag "Subscribe", class: ' choose_github btn btn-default' %>
        </p>
      <% end %>

      </div>
    <% end %>

    <p>
      <%= link_to "Back to Github Search", new_github_path %>
      <br>
      <%= link_to "See your Stream", "/" %>
    </p>
</div