config/routes.rb
Rails.application.routes.draw do

  get "/",                          to: "home#index",           as: :root

  get "/users",                     to: "users#index",          as: :users
  get "/users/new",                 to: "users#new",            as: :new_user
  post "/users/create",             to: "users#create"
  get "users/:id",                  to: "users#show",           as: :user

  get "/login",                     to: "sessions#new",         as: :login

  get "/auth/:provider/callback",   to: "sessions#create",      as: :connect
  post "/auth/:developer/callback", to: "sessions#create"
  get "/logout",                    to: "sessions#destroy",     as: :logout

  get '/vimeo/index',               to: "vimeo#index",          as: :vimeo
  get '/vimeo/search',              to: "vimeo#search",         as: :vimeo_search
  get '/vimeo/new',                 to: "vimeo#new",            as: :new_vimeo
  post '/vimeo/create',             to: "vimeo#create",         as: :create_vimeo
  get '/vimeo/update',              to: "vimeo#update"
  patch '/vimeo/edit',              to: "vimeo#edit"
  delete '/vimeo/destroy',          to: "vimeo#destroy"
  get '/vimeo/show',                to: "vimeo#show",           as: :show_vimeo

  get '/twitter/new',               to: 'twitter#new',          as: :new_twitter
  get '/twitter/search',            to: 'twitter#show',         as: :twitter_search
  post '/twitter/:feed_uid',        to: 'twitter#create',       as: :twitter

  get '/instagram/index',           to: "instagram#index",      as: :instagram
  get '/instagram/search',          to: "instagram#search",     as: :instagram_search
  get '/instagram/new',             to: "instagram#new",        as: :new_instagram
  post '/instagram/new',            to: "instagram#create"
  get '/instagram/show',            to: "instagram#show",       as: :show_instagram

  get '/githubs/new',               to: 'githubs#new',          as: :new_github
  get '/githubs/search',            to: 'githubs#show',         as: :githubs_search
  post '/githubs/',                 to: 'githubs#create',       as: :github
  get '/githubs/feed',              to: 'githubs#feed'

  post 'subscriptions/:feed_uid',   to: 'subscriptions#create', as: :subscription

end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController

  def index
    # client = Instagram.client(:access_token => session[:access_token])
  end

  def show #showing who they follow.
    create_instagram_client
    find_provider
  end
    #if you want to pull in a users feed:
    #instagram_feed = current_user.feeds.where(provider: "instagram")
    #@user = Instagram.client.user_recent_media(1574083)

  def search
    # client = Instagram.client(:access_token => session[:access_token])
    create_instagram_client
    find_provider
    @srch = params[:q]
    @feed = Instagram.client.user_search(@srch)

  end

  def create
    find_provider
    create_instagram_client
    @feed = Feed.find_by_uid(params[:feed_uid])
    if @feed
      current_user.subscriptions.create(feed_id: @feed.id)
    else
      current_user.feeds.create(provider: params["controller"],
                              uid: params[:feed_uid]) # missing username
    end
  end

  private

  def find_provider
    @provider = Provider.find_by_name_and_user_id("instagram", session[:user_id])
  end

  def create_instagram_client
    find_provider
    
    Instagram.configure do |config|
      config.client_id = ENV["INSTAGRAM_CLIENT_ID"]
      config.client_secret = ENV["INSTAGRAM_API_SECRET"]
      config.access_token =  @provider.token
    end
  end



end


# SIDE:
# create_instagram_client
# #find_provider
# instagram_feeds = current_user.feeds.where(provider: "instagram")
# instagram_feeds.each do |feed|
#   Instagram.client.user_recent_media(feed.uid.to_i).each do |ig|
#     #if ig.id.nil?
#       feed.posts.create(author_name: ig.user.name)
#     #end
#   end
# end

app/views/instagram/new.html.erb
<div class="container">
  <h1>Instagram User Search</h1>



<div class="container">
  <%= form_tag(instagram_search_path, method: "get") do %>
    <p>

      <%= text_field_tag :q, params[:q], :placeholder => "Search for user" %>
      <%= submit_tag "Go", class: 'btn btn-default' %>
      

    </p>
  <% end %>
</div>

app/views/instagram/search.html.erb
<div class="container">
  <h1>Instagram Search Results</h1>


<% @feed.each do |r| %>
  <div class='club row'>
<p><%= link_to image_tag("#{r.profile_picture}"), "http://instagram.com/#{r.username}" %>
<%= link_to r.username, "http://instagram.com/#{r.username}", target: "_blank" %>
<%= r.full_name %>

    </p>
    <div class=' col-lg-1 actions'>
      <%= button_to "Go", "/instagram/new", class: 'choose btn btn-default' %>
      <% @feed = r.id %>
      <%= hidden_field_tag "[provider_uid]", r.id, class: "info" %>

    </div>
  </div>
<% end %>

<p>
  <%= link_to "Back to Instagram Search", new_instagram_path %>
</p>

#search through what instagram returns during the search, then use that same build out for a feed to return
#that specific persons feed. 